//########################################################################--------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//########################################################################--------------------------

namespace ASM_FORM_CLIENT.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class SocketClientConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static SocketClientConfig defaultInstance = ((SocketClientConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SocketClientConfig())));
        
        public static SocketClientConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.4")]
        public string HOST {
            get {
                return ((string)(this["HOST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4444")]
        public int PORT {
            get {
                return ((int)(this["PORT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2048")]
        public int BUFFER_SIZE {
            get {
                return ((int)(this["BUFFER_SIZE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TOTAL_CONNECTION {
            get {
                return ((int)(this["TOTAL_CONNECTION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\LogForSaeaTest\\Client\\")]
        public string LOG_FILE_PATH {
            get {
                return ((string)(this["LOG_FILE_PATH"]));
            }
        }
    }
}
